### ISSUE TITLE
Patch is missing to build tinycore container image

### ISSUE THREAD

**Issue by malikbenkirane** [boot2podman/boot2podman#22]
Making the container image for tinycore fails because `patch` is no longer in alpine base container anymore 
-- or that is at least the only explanation I've found

The fix is easy as there is a package for that : https://pkgs.alpinelinux.org/packages?name=patch&branch=v3.12

PR coming very soon

**Comment by afbjorklund** [comment]
Thanks, should address when building the new version (with tinycore 11.1 and podman 2.0)

**Comment by malikbenkirane** [comment]
I addressed a pull request to https://github.com/tatsushid/docker-tinycore/pull/12
