### ISSUE TITLE
Does not work mounted as a SATA drive in VirtualBox

### ISSUE THREAD

**Issue by jeffmaury** [boot2podman/boot2podman#8]
I tried to duplicate my docker-machine VirtualBox and mounted the ISO as a SATA drive but then VirtualBox complains it cannot found bootable devices

**Comment by afbjorklund** [comment]
Hmm, the ISO is supposed to be mounted as a "cdrom" and the IMG is supposed to be a disk (eventually).

For me, the CD shows up under "IDE" (2nd master) and the Disk shows up under "SATA" (port 0).

There's no special features yet, but if you attach a disk image (and format it) it should show up under `/mnt`

I can see `/mnt/sr0` (not mounted by default), and `/mnt/sda1` which is where I keep my `tce/` as well.

**Comment by afbjorklund** [comment]
Apparently this is a known error with Tiny Core Linux, seems to be in the forums.

Or maybe there is a kernel module or boot config missing, either way: IDE for now

**Comment by afbjorklund** [comment]
Added to README, thanks!
