### ISSUE TITLE
/etc/subuid: no such file or directory on VirtualBox

### ISSUE THREAD

**Issue by jeffmaury** [boot2podman/boot2podman#9]
Once I mounted the ISO as IDE drive, then each time I issue a `podman` command, I get:
`/etc/subuid: no such file or directory on VirtualBox
`
then
`cannot read argv: No such file or directory`

**Comment by afbjorklund** [comment]
This is "normal", for now you need to run everything with `sudo podman`.

See https://github.com/boot2podman/boot2podman/issues/5, and https://github.com/containers/libpod/issues/1755 about improving the error message

**Comment by afbjorklund** [comment]
The new image has support for running rootless containers

It's not really recommended, but now it should be possible

**Comment by afbjorklund** [comment]
Was fixed in `v0.16`

Closing this issue...
